# Generated by Django 5.2.9 on 2026-01-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_add_product',
            field=models.BooleanField(default=False, verbose_name='Can Add Product'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_adjust_stock',
            field=models.BooleanField(default=False, verbose_name='Can Adjust Stock'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_cancel_invoice',
            field=models.BooleanField(default=False, verbose_name='Can Cancel Invoice'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_create_invoice',
            field=models.BooleanField(default=True, verbose_name='Can Create Invoice'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_delete_product',
            field=models.BooleanField(default=False, verbose_name='Can Delete Product'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit_product',
            field=models.BooleanField(default=False, verbose_name='Can Edit Product'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_categories',
            field=models.BooleanField(default=False, verbose_name='Can Manage Categories'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_customers',
            field=models.BooleanField(default=True, verbose_name='Can Manage Customers'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='Can Manage Users'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_billing',
            field=models.BooleanField(default=True, verbose_name='Can View Billing'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_view_inventory',
            field=models.BooleanField(default=True, verbose_name='Can View Inventory'),
        ),
    ]
