# Generated by Django 5.2.9 on 2026-01-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, default='', help_text='2-3 letter code for SKU generation (e.g., TS for T-Shirt)', max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('BK', 'Black'), ('WH', 'White'), ('RD', 'Red'), ('BL', 'Blue'), ('GR', 'Green'), ('GY', 'Grey'), ('NV', 'Navy'), ('PN', 'Pink'), ('YL', 'Yellow'), ('OR', 'Orange'), ('PR', 'Purple'), ('BR', 'Brown'), ('BG', 'Beige'), ('MR', 'Maroon'), ('TL', 'Teal')], default='BK', help_text='Primary color', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('U', 'Unisex')], default='U', help_text='Target gender', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('SU', 'Summer'), ('WI', 'Winter'), ('SP', 'Spring'), ('FA', 'Fall'), ('AY', 'All Year')], default='AY', help_text='Season collection', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double XL'), ('XXXL', 'Triple XL'), ('FS', 'Free Size')], default='M', help_text='Size', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Auto-generated. Format: GRK-SEASON-CATEGORY-GENDER-COLOR-SIZE-SERIAL', max_length=50, unique=True, verbose_name='SKU'),
        ),
    ]
